version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    working_dir: /app
    volumes:
      - './app:/app'
    environment:
      TOKEN: ${TOKEN}
      ROLE_LIST: ${ROLE_LIST}
      TRIGGER: ${TRIGGER}
