version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    working_dir: /app
    volumes:
      - './apps/bot:/app'
    environment:
      TOKEN: ${TOKEN}
      ROLE_LIST: ${ROLE_LIST}
      MUSIC_CHANNEL: ${MUSIC_CHANNEL}
      TRIGGER: ${TRIGGER}
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_LOGIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_LOGIN}:${MONGO_PASSWORD}@mongo:27017/
