version: '3.7'

services:
  discordbot:
    build:
      context: ../../.
      dockerfile: build/docker/prod/Dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_TARGET: ${DISCORD_TARGET}
      ACCESS_ROLE_LIST: ${ACCESS_ROLE_LIST}
      MUSIC_CHANNEL_LIST: ${MUSIC_CHANNEL_LIST}
