version: '3.7'

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    working_dir: /app
    volumes:
      - './apps/bot:/app'
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_TARGET: ${DISCORD_TARGET}
      ACCESS_ROLE_LIST: ${ACCESS_ROLE_LIST}
      MUSIC_CHANNEL_LIST: ${MUSIC_CHANNEL_LIST}
